%fathers
father(nikolaj_timofeev, daniil_kulagin).
father(nikolaj_timofeev, matvej_timofeev).
father(aleksej_timofeev, aleksandr_gromov).
father(aleksej_timofeev, nikolaj_timofeev).
father(nikolaj_kulagin, aleksej_kulagin).
father(nikolaj_kulagin, elena_kulagina).
father(aleksej_kulagin, aleksandr_kulagin).
father(aleksej_kulagin, elizaveta_kulagina).
father(aleksandr_kulagin, nikolaj_kulagin).
father(aleksandr_sokolov, lidiya_sokolova).
father(vladimir_timofeev, aleksej_timofeev).
father(vasilij_kurov, lidiya_timofeeva).
father(evgenij_timofeev, vladimir_timofeev).
father(dmitrij_timofeev, evgenij_timofeev).
father(nikita_timofeev, dmitrij_timofeev).
father(dmitrij_kurov, vasilij_kurov).
father(daniil_kurov, dmitrij_kurov).
father(nikolaj_skripkina, elena_skripkina).
father(ivan_kurov, valeriya_kurova).
father(daniil_kurov, ivan_kurov).
father(aleksej_shcheglov, anna_shcheglova).
father(nikolaj_vintovkin, zinaida_vintovkina).
father(aleksej_vintovkin, nikolaj_vintovkin).
father(valerij_vintovkin, aleksej_vintovkin).
father(mihail_kazakov, mariya_kazakova).
father(artyom_kiselyov, arina_kiselyova).
father(andrej_kiselyov, artyom_kiselyov).
father(nikolaj_pushkin, natalya_pushkin).
father(mihail_kurov, daniil_kurov).
father(dmitrij_petruhin, vasilisa_petruhina).
father(pavel_palyonov, alisa_palyonova).
father(andrej_palyonov, pavel_palyonov).
father(maksim_yagodkin, veronika_yagodka).
father(dmitrij_gromov, pelageya_gromova).
father(nikita_gromov, dmitrij_gromov).
father(matvej_gromov, nikita_gromov).
father(ravil_sapihanov, elena_sapihanova).
father(ilya_korobkin, elena_korobkina).
father(ivan_korobkin, ilya_korobkin).
father(semyon_karpuhin, tatyana_karpuhina).
%mothers
mother(elena_kulagina, daniil_kulagin).
mother(elena_kulagina, matvej_timofeev).
mother(lidiya_timofeeva, aleksandr_gromov).
mother(lidiya_timofeeva, nikolaj_timofeev).
mother(lidiya_sokolova, aleksej_kulagin).
mother(lidiya_sokolova, elena_kulagina).
mother(larisa_gakova, aleksandr_kulagin).
mother(larisa_gakova, elizaveta_kulagina).
mother(darya_sdobnuhina, nikolaj_kulagin).
mother(praskovya_sokolova, lidiya_sokolova).
mother(zinaida_vintovkina, aleksej_timofeev).
mother(pelageya_gromova, lidiya_timofeeva).
mother(valeriya_kurova, vladimir_timofeev).
mother(elena_skripkina, evgenij_timofeev).
mother(liza_nikulina, dmitrij_timofeev).
mother(alisa_palyonova, vasilij_kurov).
mother(vasilisa_petruhina, dmitrij_kurov).
mother(lidiya_blistunova, elena_skripkina).
mother(anna_shcheglova, valeriya_kurova).
mother(aleksandra_kirilenko, ivan_kurov).
mother(larisa_shcheglova, anna_shcheglova).
mother(arina_kiselyova, zinaida_vintovkina).
mother(mariya_kazakova, nikolaj_vintovkin).
mother(darya_kuznecova, aleksej_vintovkin).
mother(valeriya_fedorenko, mariya_kazakova).
mother(natalya_pushkin, arina_kiselyova).
mother(anastasiya_pavlova, artyom_kiselyov).
mother(elena_rezvyakova, natalya_pushkin).
mother(alina_nikulina, daniil_kurov).
mother(alina_nikitina, vasilisa_petruhina).
mother(veronika_yagodka, alisa_palyonova).
mother(anna_smirnova, pavel_palyonov).
mother(ekaterina_mamaeva, veronika_yagodka).
mother(elena_korobkina, pelageya_gromova).
mother(elena_sapihanova, dmitrij_gromov).
mother(anastasiya_sanchenko, nikita_gromov).
mother(dzhennet_rozyeva, elena_sapihanova).
mother(tatyana_karpuhina, elena_korobkina).
mother(galina_minenko, ilya_korobkin).
mother(anastasiya_konon, tatyana_karpuhina).
